#pragma once

#define CONFIG_FILE_NAME "guess_cfg.txt"

#define TOTAL_MIN_RAND_NUMBER 1
#define TOTAL_MAX_RAND_NUMBER 20000

#define DEFAULT_MAX_RAND_NUMBER 1000

#define LVL1_MAX_RAND_NUMBER 100
#define LVL2_MAX_RAND_NUMBER 1500
#define LVL3_MAX_RAND_NUMBER 15000